/**
 * @file RouteAggregator.h
 * @brief EIGRP route aggregation and summarization.
 */

#ifndef EIGRP_ROUTE_AGGREGATOR_H
#define EIGRP_ROUTE_AGGREGATOR_H

#include <map>
#include <set>
#include <limits>
#include <IPAddress.h>

namespace types { struct IPAddress; }

namespace routing::eigrp
{
class EigrpInterface;

struct TopologyEntry;
struct RouteInfo;

/**
 * @brief Tracks a single configured or auto-generated summary route and the
 *        more-specific prefixes it covers.
 * @ingroup EIGRP_INTERFACE
 *
 * `SummaryRoute` is the bookkeeping record for one summary prefix on an
 * interface.  It links the synthesized @ref TopologyEntry / @ref RouteInfo
 * pair back to the set of covered more-specific prefixes and remembers the
 * best feasible distance seen across those prefixes so the summary metric can
 * be kept accurate.
 */
struct SummaryRoute
{
    TopologyEntry* summaryEntry = nullptr;          ///< Synthetic topology entry created for this summary.
    RouteInfo* summaryRoute = nullptr;              ///< Route record inside summaryEntry carrying the aggregated metric.
    bool isAuto = false;                            ///< True if this summary was generated by auto-summarization rather than a manual `ip summary-address` command.
    std::set<types::IPPrefix> summarizedRoutes = {}; ///< More-specific prefixes currently suppressed by this summary.
    uint64_t bestFD = std::numeric_limits<uint64_t>::max(); ///< Lowest feasible distance among all summarized routes; used as the summary metric.
};

/**
 * @brief Manages manual and automatic summary routes for a single EIGRP interface.
 * @ingroup EIGRP_INTERFACE
 *
 * `RouteAggregator` maintains the set of summary prefixes configured on or
 * generated for one `EigrpInterface`.  For each summary it:
 * - Synthesizes a @ref TopologyEntry and @ref RouteInfo so the summary
 *   appears in the topology table and can be advertised to neighbors.
 * - Suppresses (hides from advertisement) the more-specific prefixes that
 *   fall under the summary on the owning interface.
 * - Recalculates the summary's metric whenever a covered prefix changes, so
 *   the summary always reflects the best feasible distance of its components.
 *
 * ## Architectural Role
 * One `RouteAggregator` exists per `EigrpInterface`.  It interacts with the
 * topology table through `iface`, which provides access to the process-wide
 * `DuelEngine` and its `TopologyTable`.  The aggregator does not hold topology
 * entries directly; it stores pointers into the topology table.
 *
 * ## Lifecycle & Ownership
 * Created and destroyed with the owning `EigrpInterface`.  All pointers stored
 * in `SummaryRoute` are invalidated when the topology table is cleared or the
 * process shuts down — the destructor withdraws all summaries to clean up those
 * entries before teardown.
 *
 * @warning Pointers inside `SummaryRoute` (e.g. `summaryEntry`) become
 *          dangling if the underlying topology entry is removed without going
 *          through `withdrawSummary`.  Always withdraw summaries before clearing
 *          the topology table.
 *
 * @see EigrpInterface
 * @see TopologyEntry
 */
class RouteAggregator
{
public:
    /**
     * @brief Constructs an aggregator bound to the given interface.
     *
     * @param iface The interface whose topology table and suppression state
     *              this aggregator manages.
     */
    RouteAggregator(EigrpInterface& iface);

    /**
     * @brief Withdraws all auto-generated summaries and removes their topology entries.
     *
     * Called when auto-summarization is disabled for the process so that
     * classful summary prefixes no longer appear in advertisements.
     */
    ~RouteAggregator();

    /**
     * @brief Withdraws and removes all auto-generated summary routes.
     *
     * Does not affect manually configured summaries.
     */
    void clearAutoSummaries();

    /**
     * @brief Recalculates and republishes the metric for a single summary route.
     *
     * Scans the covered more-specific prefixes to find the best feasible
     * distance and updates the summary's topology entry accordingly.
     *
     * @param r The summary route to recalculate.
     */
    void updateSummaryRoute(SummaryRoute& r);

    /**
     * @brief Recalculates and republishes metrics for a batch of summary routes.
     *
     * @param r Vector of summary routes to update.
     */
    void updateSummaryRoutes(std::vector<SummaryRoute*>& r);

    /**
     * @brief Determines whether a summary's covered set or metric has changed.
     *
     * Evaluates the current topology table against the summary prefix to
     * compute the new covered-prefix set and best feasible distance.
     *
     * @param r Summary route to evaluate.
     * @return A pair where `.first` is true if the covered set changed and
     *         `.second` is true if the metric changed.
     */
    std::pair<bool, bool> calculateSummary(SummaryRoute& r);

    /**
     * @brief Recalculates all installed summary routes on this interface.
     *
     * @param isAuto If true, only auto-generated summaries are updated;
     *               if false (default), all summaries are updated.
     */
    void updateAllSummaryRoutes(bool isAuto = false);

    /**
     * @brief Installs a summary route for the given prefix on this interface.
     *
     * Creates a synthetic topology entry for `prefix`, calculates the initial
     * covered set and metric, and suppresses the covered more-specific prefixes.
     *
     * @param prefix The summary prefix to install.
     * @param isAuto True if this is an auto-summarization entry (default false).
     */
    void installSummary(const types::IPPrefix& prefix, bool isAuto = false);

    /**
     * @brief Installs multiple summary routes in a single operation.
     *
     * @param prefixes Set of summary prefixes to install.
     * @param isAuto   True if these are auto-summarization entries (default false).
     */
    void installSummaries(const std::set<types::IPPrefix>& prefixes, bool isAuto = false);

    /**
     * @brief Withdraws a summary route and unsuppresses its covered prefixes.
     *
     * Removes the synthetic topology entry and clears the suppression flags on
     * all previously covered more-specific prefixes so they become advertisable
     * again.
     *
     * @param prefix The summary prefix to withdraw.
     */
    void withdrawSummary(const types::IPPrefix& prefix);

    /**
     * @brief Checks whether `prefix` is currently suppressed by any summary on
     *        this interface.
     *
     * @param prefix The more-specific prefix to check.
     * @return Pointer to the @ref SummaryRoute suppressing `prefix`, or nullptr
     *         if it is not covered by any summary.
     */
    SummaryRoute* isSummarized(const types::IPPrefix& prefix);

private:
    EigrpInterface& iface;                                  ///< Interface whose topology this aggregator manages.
    std::map<types::IPPrefix, SummaryRoute> summaryRoutes;  ///< All active summaries keyed by their aggregate prefix.
};
} // namespace routing::eigrp

#endif // EIGRP_ROUTE_AGGREGATOR_H
