// BgpRegistry.h

#ifndef BGP_REGISTRY_H
#define BGP_REGISTRY_H

#include <string>

#include "IPAddress.hpp"
#include "configs/TupleSchema.hpp"
#include "configs/RegistryTypes.hpp"
#include "configs/RegistryReference.hpp"

struct buh {};

namespace Config
{
inline __uint128_t generateBgpKey(uint32_t vrf, uint32_t as, AddressFamily af)
{
    uint8_t addressFamily = af == AddressFamily::NONE ? 0
        : af == AddressFamily::IPv4 ? 1 : 2;

    __uint128_t key = 0;
    key |= __uint128_t(addressFamily) & maskU128Bits(2);
    key |= __uint128_t(vrf) << 8;
    key |= __uint128_t(as) << 40;
    return key;
}

enum class BgpBase
{
    KEEPALIVE_INTERVAL,
    HOLDTIME,
    MINIMUM_HOLDTIME,
    TRANSPORT_PATH_MTU_DISCOVERY,
    COUNT
};

using BgpBaseRegistry = SubRegistry<__uint128_t, BgpBase, buh,
    AtomicField<uint16_t, 60 CONFIG_INDEX_ARG(BgpBase::KEEPALIVE_INTERVAL)>,
    AtomicField<uint16_t, 180 CONFIG_INDEX_ARG(BgpBase::HOLDTIME)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(BgpBase::MINIMUM_HOLDTIME)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpBase::TRANSPORT_PATH_MTU_DISCOVERY)>
>;


enum class BgpNeighbor
{
    BGP_BASE,
    ACTIVATE,
    ADDITIONAL_PATHS_RECEIVE,
    ADDITIONAL_PATHS_SEND,
    ADVERTISE_ADDITIONAL_PATHS_ALL,
    ADVERTISE_ADDITIONAL_PATHS_BEST,
    ADVERTISE_ADDITIONAL_GROUP_BEST,
    ADVERTISE_BEST_EXTERNAL,
    ADVERTISE_DIVERSE_PATH_BACKUP,
    ADVERTISE_DIVERSE_PATH_MPATH,
    ADVERTISE_MAP,
    ADVERTISE_MAP_EXIST_CONDITION,
    ADVERTISE_MAP_NON_EXIST_CONDITION,
    ADVERTISE_INTERVAL,
    ALLOWAS_IN,
    ALLOWAS_IN_OCCURANCES,
    ANNOUNCE_RPKI_STATE,
    ORF_BOTH,
    ORF_RECEIVE,
    ORF_SEND,
    ORIGINATE_ROUTE_MAP,
    DESCRIPTION,
    DISABLE_CONNECTION_CHECK,
    DISTRIBUTE_LIST_IN,
    DISTRIBUTE_LIST_IN_INTERFACE,
    DISTRIBUTE_LIST_OUT,
    DISTRIBUTE_LIST_OUT_INTERFACE,
    DMZLINK_BW,
    EBGP_MULTIHOP,
    EBGP_MAX_HOP_COUNT,
    FALL_OVER,
    FALL_OVER_BFD_CHECK_CONTROL_PLANE_FAILURE,
    FALL_OVER_BFD_MULTI_HOP,
    FALL_OVER_BFD_SINGLE_HOP,
    FALL_OVER_ROUTE_MAP,
    FILTER_LIST_IN,
    FILTER_LIST_OUT,
    HAMODE_GRACEFUL_RESTART,
    INHERIT_PEER_POLICY,
    INHERIT_PEER_SESSION,
    LOCAL_AS,
    LOCAL_AS_AS,
    LOCAL_AS_NO_PREPEND,
    LOCAL_AS_REPLACE_AS,
    LOCAL_AS_DUEL_AS,
    MAXIMUM_PREFIX,
    MAXIMUM_PREFIX_THRESHOLD,
    MAXIMUM_PREFIX_RESTART,
    MAXIMUM_PREFIX_WARNING_ONLY,
    NEXT_HOP_SELF,
    NEXT_HOP_SELF_ALL,
    NEXT_HOP_UNCHANGED,
    PASSWORD,
    PATH_ATTRIBUTE,
    PEER_GROUP,
    PREFIX_LIST_IN,
    PREFIX_LIST_OUT,
    REMOTE_AS,
    REMOTE_AS_SHUTDOWN,
    REMOVE_PRIVATE_AS,
    REMOVE_PRIVATE_AS_ALL,
    ROUTE_MAP_IN,
    ROUTE_MAP_OUT,
    ROUTE_REFLECTOR_CLIENT,
    ROUTE_SERVER_CLIENT,
    ROUTE_SERVER_CLIENT_CONTEXT,
    SEND_COMMUNITY,
    SEND_COMMUNITY_BOTH,
    SEND_COMMUNITY_EXTENDED,
    SEND_COMMUNITY_STANDARD,
    SHUTDOWN,
    SLOW_PEER_DETECTION,
    SLOW_PEER_DETECTION_THRESHOLD,
    SLOW_PEER_SPLIT_UPDATE_GROUP_STATIC,
    SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC,
    SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC_PERMANENT,
    SLOW_RECONFIGURATION,
    TRANSLATE_UPDATE,
    TRANSPORT_CONNECTION_MODE,
    TRANSPORT_MULTI_SESSION,
    TTL_SEC,
    TTL_SEC_HOP,
    UNSUPPRESS_MAP,
    WEIGHT,
    COUNT
};

using BgpNeighborRegistry = SubRegistry<__uint128_t, BgpNeighbor, buh,
    ReferenceContainer<BgpBaseRegistry CONFIG_INDEX_ARG(BgpNeighbor::BGP_BASE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ACTIVATE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADDITIONAL_PATHS_RECEIVE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADDITIONAL_PATHS_SEND)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_ADDITIONAL_PATHS_ALL)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_ADDITIONAL_PATHS_BEST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_ADDITIONAL_GROUP_BEST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_BEST_EXTERNAL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_DIVERSE_PATH_BACKUP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_DIVERSE_PATH_MPATH)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_MAP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_MAP_EXIST_CONDITION)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_MAP_NON_EXIST_CONDITION)>,
    AtomicField<uint16_t, 30 CONFIG_INDEX_ARG(BgpNeighbor::ADVERTISE_INTERVAL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ALLOWAS_IN)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(BgpNeighbor::ALLOWAS_IN_OCCURANCES)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ANNOUNCE_RPKI_STATE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ORF_BOTH)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ORF_RECEIVE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ORF_SEND)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ORIGINATE_ROUTE_MAP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::DESCRIPTION)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::DISABLE_CONNECTION_CHECK)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::DISTRIBUTE_LIST_IN)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(BgpNeighbor::DISTRIBUTE_LIST_IN_INTERFACE)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::DISTRIBUTE_LIST_OUT)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(BgpNeighbor::DISTRIBUTE_LIST_OUT_INTERFACE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::DMZLINK_BW)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::EBGP_MULTIHOP)>,
    AtomicField<uint8_t, 1 CONFIG_INDEX_ARG(BgpNeighbor::EBGP_MAX_HOP_COUNT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::FALL_OVER)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::FALL_OVER_BFD_CHECK_CONTROL_PLANE_FAILURE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::FALL_OVER_BFD_MULTI_HOP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::FALL_OVER_BFD_SINGLE_HOP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::FALL_OVER_ROUTE_MAP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::FILTER_LIST_IN)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::FILTER_LIST_OUT)>,
    OptionalAtomicField<bool CONFIG_INDEX_ARG(BgpNeighbor::HAMODE_GRACEFUL_RESTART)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::INHERIT_PEER_POLICY)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::INHERIT_PEER_SESSION)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::LOCAL_AS)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(BgpNeighbor::LOCAL_AS_AS)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::LOCAL_AS_NO_PREPEND)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::LOCAL_AS_REPLACE_AS)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::LOCAL_AS_DUEL_AS)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(BgpNeighbor::MAXIMUM_PREFIX)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(BgpNeighbor::MAXIMUM_PREFIX_THRESHOLD)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(BgpNeighbor::MAXIMUM_PREFIX_RESTART)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::MAXIMUM_PREFIX_WARNING_ONLY)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::NEXT_HOP_SELF)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::NEXT_HOP_SELF_ALL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::NEXT_HOP_UNCHANGED)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::PASSWORD)>,
    ValueField<std::vector<std::tuple<
        bool,    // true = discard, false = treat-as-withdraw
        bool,    // isRanged
        uint8_t, // start
        uint8_t  // end
    >> CONFIG_INDEX_ARG(BgpNeighbor::PATH_ATTRIBUTE)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::PEER_GROUP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::PREFIX_LIST_IN)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::PREFIX_LIST_OUT)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(BgpNeighbor::REMOTE_AS)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::REMOTE_AS_SHUTDOWN)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::REMOVE_PRIVATE_AS)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::REMOVE_PRIVATE_AS_ALL)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ROUTE_MAP_IN)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ROUTE_MAP_OUT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ROUTE_REFLECTOR_CLIENT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::ROUTE_SERVER_CLIENT)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::ROUTE_SERVER_CLIENT_CONTEXT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SEND_COMMUNITY)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SEND_COMMUNITY_BOTH)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SEND_COMMUNITY_EXTENDED)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SEND_COMMUNITY_STANDARD)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SHUTDOWN)>, // ad graceful
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SLOW_PEER_DETECTION)>,
    AtomicField<uint16_t, 60 CONFIG_INDEX_ARG(BgpNeighbor::SLOW_PEER_DETECTION_THRESHOLD)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SLOW_PEER_SPLIT_UPDATE_GROUP_STATIC)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC)>, // false static
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC_PERMANENT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::SLOW_RECONFIGURATION)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::TRANSLATE_UPDATE)>,
    OptionalAtomicField<bool CONFIG_INDEX_ARG(BgpNeighbor::TRANSPORT_CONNECTION_MODE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::TRANSPORT_MULTI_SESSION)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(BgpNeighbor::TTL_SEC)>,
    AtomicField<uint8_t, 1 CONFIG_INDEX_ARG(BgpNeighbor::TTL_SEC_HOP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(BgpNeighbor::UNSUPPRESS_MAP)>,
    AtomicField<uint16_t, 0 CONFIG_INDEX_ARG(BgpNeighbor::WEIGHT)>
>;

enum class Bgp
{
    AGGREGATE_ADDRESS,
    BGP_BASE,
    BGP_ADDITIONAL_PATHS_INSTALL,
    BGP_ADDITIONAL_PATHS_RECEIVE,
    BGP_ADDITIONAL_PATHS_SELECT,
    BGP_ADDITIONAL_PATHS_SELECT_ALL,
    BGP_ADDITIONAL_PATHS_SELECT_BACKUP,
    BGP_ADDITIONAL_PATHS_SELECT_BEST, // uint8
    BGP_ADDITIONAL_PATHS_SELECT_BEST_EXTERNAL,
    BGP_ADDITIONAL_PATHS_SELECT_GROUP_BEST,
    BGP_ADVERTISE_BEST_EXTERNAL,
    BGP_AGGREGATE_TIMER,
    BGP_ALWAYS_COMPARE_MED,
    BGP_AS_DOT_NOTATION,
    BGP_BEST_PATH_COMPARE_ROUTER_ID,
    BGP_BEST_PATH_COST_COMMUNITY_IGNORE,
    BGP_BEST_PATH_IGP_METRIC_IGNORE,
    BGP_BEST_PATH_MED_CONFED,
    BGP_BEST_PATH_MED_MISSING_AS_WORST,
    BGP_BEST_PATH_PREFIX_VALIDATE_ALLOW_INVALID,
    BGP_CLIENT_TO_CLIENT_REFLECTION,
    BGP_CLUSTER_ID,
    BGP_CONFEDERATION_IDENTIFIER,
    BGP_CONFEDERATION_PEERS,
    BGP_CONSISTENCY_CHECKER_ERROR_MESSAGE_INTERVAL,
    BGP_DAMPENING,
    BGP_DAMPENING_HALF_LIFE,
    BGP_DAMPENING_REUSE_THRESHOLD,
    BGP_DAMPENING_SUPPRESS_THRESHOLD,
    BGP_DAMPENING_MAXIMUM_SUPPRESS_TIME,
    BGP_DAMPENING_ROUTE_MAP,
    BGP_DETERMINISTIC_MED,
    BGP_DMZLINK_BW,
    BGP_ENFORCE_FIRST_AS,
    BGP_ENHANCED_ERROR,
    BGP_FAST_EXTERNAL_FAILOVER,
    BGP_GRACEFUL_RESTART,
    BGP_GRACEFUL_RESTART_EXTENDED,
    BGP_GRACEFUL_RESTART_RESTART_TIME,
    BGP_GRACEFUL_RESTART_STALEPATH_TIME,
    BGP_INJECT_MAP,
    BGP_INJECT_MAP_EXIST_MAP,
    BGP_INJECT_MAP_COPY_ATTRIBUTES,
    BGP_LISTEN,
    BGP_LISTEN_LIMIT,
    BGP_LISTEN_RANGE,
    BGP_LOG_NEIGHBOR_CHANGES,
    BGP_MAX_AS_LIMIT,
    BGP_MAX_COMMUNITY_LIMIT,
    BGP_MAX_EXT_COMMUNITY_LIMIT,
    BGP_NEXT_HOP_ROUTE_MAP,
    BGP_NEXT_HOP_TRIGGER_DELAY,
    BGP_NEXT_HOP_TRACKING,
    BGP_NOPEERUP_DELAY_COLD_BOOT,
    BGP_NOPEERUP_DELAY_NSF_SWITCHOVER,
    BGP_NOPEERUP_DELAY_POST_BOOT,
    BGP_NOPEERUP_DELAY_USER_INITIATED,
    BGP_RECURSIVE_HOST,
    BGP_REDISTRIBUTE_INTERNAL,
    BGP_REFRESH_MAX_EOR_TIME,
    BGP_REFRESH_STALEPATH_TIME,
    BGP_REGEX_DETERMINISTIC,
    BGP_ROUTE_MAP_PRIORITY,
    BGP_ROUTER_ID,
    BGP_RPKI_SERVER,
    BGP_SCAN_TIME,
    BGP_SLOW_PEER_DETECTION,
    BGP_SLOW_PEER_DETECTION_THRESHOLD,
    BGP_SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC,
    BGP_SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC_PERMANENT,
    BGP_SOFT_RECONFIG_BACKUP,
    BGP_SUPPRESS_INACTIVE,
    BGP_UPDATE_DELAY,
    DEFAULT_ORIGINATE,
    DEFAULT_METRIC,
    DISTANCE_RANGE,
    DISTANCE_BGP_EXTERNAL,
    DISTANCE_BGP_INTERNAL,
    DISTANCE_BGP_LOCAL,
    DISTANCE_MBGP_EXTERNAL,
    DISTANCE_MBGP_INTERNAL,
    DISTANCE_MBGP_LOCAL,
    DISTRIBUTE_LIST_IN,
    DISTRIBUTE_LIST_IN_INTERFACE,
    DISTRIBUTE_LIST_IN_PREFIX,
    DISTRIBUTE_LIST_OUT,
    DISTRIBUTE_LIST_OUT_INTERFACE,
    DISTRIBUTE_LIST_OUT_PREFIX,
    DISTRIBUTE_LIST_GATEWAY,
    MAXIMUM_PATHS_EBGP,
    MAXIMUM_PATHS_IBGP,
    NEIGHBOR,
    NETWORK,
    ROUTE_SERVER_CONTEXT,
    TABLE_MAP,
    TABLE_MAP_FILTER,
    TEMPLATE_PEER_POLICY,
    TEMPLATE_PEER_SESSION,
    COUNT
};

#define BGP_AGGREGATE_ADDRESS_FIELDS(X) \
    X(IPPrefix,    prefix) \
    X(std::string, advertiseMap) \
    X(bool,        asConfedSet) \
    X(std::string, attributeMap) \
    X(std::string, routeMap) \
    X(bool,        summaryOnly) \
    X(std::string, suppressMap)

DEFINE_TUPLE_SCHEMA(BgpAggregateAddress, BGP_AGGREGATE_ADDRESS_FIELDS)

using BgpRegistry = SubRegistry<__uint128_t, Bgp, buh,
    ValueField<std::vector<BgpAggregateAddress::Tuple> CONFIG_INDEX_ARG(Bgp::AGGREGATE_ADDRESS)>,
    ReferenceContainer<BgpBaseRegistry CONFIG_INDEX_ARG(Bgp::BGP_BASE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_INSTALL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_RECEIVE)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT_ALL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT_BACKUP)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT_BEST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT_BEST_EXTERNAL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADDITIONAL_PATHS_SELECT_GROUP_BEST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ADVERTISE_BEST_EXTERNAL)>,
    AtomicField<uint8_t, 30 CONFIG_INDEX_ARG(Bgp::BGP_AGGREGATE_TIMER)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ALWAYS_COMPARE_MED)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_AS_DOT_NOTATION)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_COMPARE_ROUTER_ID)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_COST_COMMUNITY_IGNORE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_IGP_METRIC_IGNORE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_MED_CONFED)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_MED_MISSING_AS_WORST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_BEST_PATH_PREFIX_VALIDATE_ALLOW_INVALID)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_CLIENT_TO_CLIENT_REFLECTION)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::BGP_CLUSTER_ID)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::BGP_CONFEDERATION_IDENTIFIER)>,
    ValueField<std::vector<uint32_t> CONFIG_INDEX_ARG(Bgp::BGP_CONFEDERATION_PEERS)>,
    AtomicField<uint32_t, 60 CONFIG_INDEX_ARG(Bgp::BGP_CONSISTENCY_CHECKER_ERROR_MESSAGE_INTERVAL)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING)> ,
    AtomicField<uint8_t, 15 CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING_HALF_LIFE)>,
    AtomicField<uint16_t, 750 CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING_REUSE_THRESHOLD)>,
    AtomicField<uint16_t, 2000 CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING_SUPPRESS_THRESHOLD)>,
    AtomicField<uint8_t, 60 CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING_MAXIMUM_SUPPRESS_TIME)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::BGP_DAMPENING_ROUTE_MAP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_DETERMINISTIC_MED)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_DMZLINK_BW)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_ENFORCE_FIRST_AS)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ENHANCED_ERROR)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_FAST_EXTERNAL_FAILOVER)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_GRACEFUL_RESTART)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_GRACEFUL_RESTART_EXTENDED)>,
    AtomicField<uint16_t, 120 CONFIG_INDEX_ARG(Bgp::BGP_GRACEFUL_RESTART_RESTART_TIME)>,
    AtomicField<uint16_t, 360 CONFIG_INDEX_ARG(Bgp::BGP_GRACEFUL_RESTART_STALEPATH_TIME)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::BGP_INJECT_MAP)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::BGP_INJECT_MAP_EXIST_MAP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_INJECT_MAP_COPY_ATTRIBUTES)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_LISTEN)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_LISTEN_LIMIT)>,
    ValueField<std::vector<std::tuple<uint32_t, uint32_t, std::string>> CONFIG_INDEX_ARG(Bgp::BGP_LISTEN_RANGE)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_LOG_NEIGHBOR_CHANGES)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(Bgp::BGP_MAX_AS_LIMIT)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_MAX_COMMUNITY_LIMIT)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_MAX_EXT_COMMUNITY_LIMIT)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::BGP_NEXT_HOP_ROUTE_MAP)>,
    OptionalValueField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_NEXT_HOP_TRIGGER_DELAY)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_NEXT_HOP_TRACKING)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_NOPEERUP_DELAY_COLD_BOOT)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_NOPEERUP_DELAY_NSF_SWITCHOVER)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_NOPEERUP_DELAY_POST_BOOT)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_NOPEERUP_DELAY_USER_INITIATED)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_RECURSIVE_HOST)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_REDISTRIBUTE_INTERNAL)>,
    AtomicField<uint16_t, 60 CONFIG_INDEX_ARG(Bgp::BGP_REFRESH_MAX_EOR_TIME)>,
    AtomicField<uint16_t, 120 CONFIG_INDEX_ARG(Bgp::BGP_REFRESH_STALEPATH_TIME)>,
    AtomicField<bool, true CONFIG_INDEX_ARG(Bgp::BGP_REGEX_DETERMINISTIC)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_ROUTE_MAP_PRIORITY)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::BGP_ROUTER_ID)>,
    ValueField<std::vector<std::tuple<
        IPAddress,
        uint16_t, // port
        uint16_t, // refresh time
        std::string, // ssh username
        std::string // ssh password
    >> CONFIG_INDEX_ARG(Bgp::BGP_RPKI_SERVER)>,
    AtomicField<uint8_t, 60 CONFIG_INDEX_ARG(Bgp::BGP_SCAN_TIME)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_SLOW_PEER_DETECTION)>,
    AtomicField<uint16_t, 60 CONFIG_INDEX_ARG(Bgp::BGP_SLOW_PEER_DETECTION_THRESHOLD)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC)>, // false = static
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_SLOW_PEER_SPLIT_UPDATE_GROUP_DYNAMIC_PERMANENT)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_SOFT_RECONFIG_BACKUP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::BGP_SUPPRESS_INACTIVE)>,
    OptionalAtomicField<uint16_t CONFIG_INDEX_ARG(Bgp::BGP_UPDATE_DELAY)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::DEFAULT_ORIGINATE)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::DEFAULT_METRIC)>,
    ValueField<std::vector<std::tuple<uint8_t, std::vector<IPPrefix, std::string>>> CONFIG_INDEX_ARG(Bgp::DISTANCE_RANGE)>,
    AtomicField<uint8_t, 20 CONFIG_INDEX_ARG(Bgp::DISTANCE_BGP_EXTERNAL)>,
    AtomicField<uint8_t, 200 CONFIG_INDEX_ARG(Bgp::DISTANCE_BGP_INTERNAL)>,
    AtomicField<uint8_t, 200 CONFIG_INDEX_ARG(Bgp::DISTANCE_BGP_LOCAL)>,
    AtomicField<uint8_t, 20 CONFIG_INDEX_ARG(Bgp::DISTANCE_MBGP_EXTERNAL)>,
    AtomicField<uint8_t, 200 CONFIG_INDEX_ARG(Bgp::DISTANCE_MBGP_INTERNAL)>,
    AtomicField<uint8_t, 200 CONFIG_INDEX_ARG(Bgp::DISTANCE_MBGP_LOCAL)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_IN)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_IN_INTERFACE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_IN_PREFIX)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_OUT)>,
    OptionalAtomicField<uint32_t CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_OUT_INTERFACE)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_OUT_PREFIX)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::DISTRIBUTE_LIST_GATEWAY)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(Bgp::MAXIMUM_PATHS_EBGP)>,
    OptionalAtomicField<uint8_t CONFIG_INDEX_ARG(Bgp::MAXIMUM_PATHS_IBGP)>,
    OwnedListField<BgpNeighborRegistry, __uint128_t CONFIG_INDEX_ARG(Bgp::NEIGHBOR)>,
    ValueField<std::vector<std::tuple<IPPrefix, bool, std::string>> CONFIG_INDEX_ARG(Bgp::NETWORK)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::ROUTE_SERVER_CONTEXT)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::TABLE_MAP)>,
    AtomicField<bool, false CONFIG_INDEX_ARG(Bgp::TABLE_MAP_FILTER)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::TEMPLATE_PEER_POLICY)>,
    OptionalValueField<std::string CONFIG_INDEX_ARG(Bgp::TEMPLATE_PEER_SESSION)>
>;
}

#endif // OSPF_REGISTRY_H
