/**
 * @file RegistryDefaultTable.hpp
 * @brief Per-field default values and the traits that look them up.
 * @ingroup CONFIG
 *
 * Holds the declarations shared by SubRegistry.hpp and RegistryBuilder.hpp.
 * They live here rather than in RegistryBuilder.hpp because SubRegistry.hpp
 * needs them and RegistryBuilder.hpp includes SubRegistry.hpp -- putting them
 * in the builder would make that include cycle.
 *
 * DEFINE_CONFIG_GROUP specializes Entry<ENUM, E> for each field declared with a
 * default; everything else falls through to the primary template below, which
 * reports has == false and value-initializes.
 */

// RegistryDefaultTable.hpp

#ifndef REGISTRY_DEFAULT_TABLE_HPP
#define REGISTRY_DEFAULT_TABLE_HPP

#include <cstdint>
#include <string_view>
#include <type_traits>

namespace config
{
/// @brief Maps a config enum to its generated table of field-name hashes.
template <typename ENUM>
struct HashRegistry;

/**
 * @brief Default value for one enum field.
 *
 * The primary template is the "no default declared" case. Specializations are
 * generated by DEFINE_CONFIG_GROUP for fields that declare one.
 */
template <typename ENUM, ENUM E>
struct Entry
{
    static constexpr bool has = false;

    template <typename T>
    static constexpr T get() noexcept
    {
        if constexpr (std::is_pointer_v<T>)
            return nullptr;
        else
            return T{};
    }
};

/// @brief True when a default was declared for this field.
template <typename ENUM, ENUM E>
inline constexpr bool hasV = Entry<ENUM, E>::has;

/// @brief The declared default; a compile error if there is none.
template <typename T, auto E>
constexpr T getV() noexcept
{
    using ENUM = decltype(E);
    static_assert(Entry<ENUM, E>::has, "No default exists for this enum entry.");
    return Entry<ENUM, E>::template get<T>();
}

// Peels pointers, references and const off a field type to get the stored type.
template <typename T>
struct Strip
{
    using type = T;
};

template <typename T>
struct Strip<T*>
{
    using type = typename Strip<T>::type;
};

template <typename T>
struct Strip<T&>
{
    using type = typename Strip<T>::type;
};

template <typename T>
struct Strip<T&&>
{
    using type = typename Strip<T>::type;
};

template <typename T>
struct Strip<const T>
{
    using type = typename Strip<T>::type;
};

template <typename T>
using DefType = typename Strip<T>::type;

/// @brief FNV-1a over a field name, used to look fields up by string.
static constexpr uint32_t tokenHash(std::string_view sv)
{
    uint32_t h = 0x811C9DC5;
    for (char c : sv)
    {
        h ^= static_cast<uint32_t>(c);
        h *= 0x01000193;
    }
    return h;
}
}

#endif // REGISTRY_DEFAULT_TABLE_HPP
