/**
 * @file RegistryDefaultTable.hpp
 * @brief Per-field default values and the traits that look them up.
 * @ingroup CONFIG
 *
 * One job: given a field, what value does it start at.
 *
 * A default is attached to a field by specializing Entry<ENUM, FIELD>. There are
 * two ways that happens, and they produce identical specializations so a
 * registry can move between them without its defaults changing meaning:
 *
 *   - DEFINE_CONFIG_GROUP, for a registry whose FIELD_LIST carries each default
 *     inline. It emits the specializations itself.
 *   - CONFIG_DEFAULT_TABLE, for a registry that keeps a separate default list.
 *
 * A field with no declared default falls through to the primary template, which
 * reports has == false and value-initializes.
 *
 * Declared here rather than in RegistryBuilder.hpp because SubRegistry.hpp needs
 * these and the builder includes SubRegistry.hpp; the other direction would be a
 * cycle.
 */

// RegistryDefaultTable.hpp

#ifndef REGISTRY_DEFAULT_TABLE_HPP
#define REGISTRY_DEFAULT_TABLE_HPP

#include <type_traits>

#include "configs/RegistryTraits.hpp" // IWYU pragma: export -- RegistryOf, HashRegistry

namespace config
{
/**
 * @brief Default value for one enum field.
 *
 * The primary template is the "no default declared" case. Specializations are
 * generated by DEFINE_CONFIG_GROUP or CONFIG_DEFAULT_TABLE for fields that
 * declare one.
 */
template <typename ENUM, ENUM E>
struct Entry
{
    static constexpr bool has = false;

    template <typename T>
    static constexpr T get() noexcept
    {
        if constexpr (std::is_pointer_v<T>)
            return nullptr;
        else
            return T{};
    }
};

/// @brief True when a default was declared for this field.
template <typename ENUM, ENUM E>
inline constexpr bool hasV = Entry<ENUM, E>::has;

/// @brief The declared default; a compile error if there is none.
template <typename T, auto E>
constexpr T getV() noexcept
{
    using ENUM = decltype(E);
    static_assert(Entry<ENUM, E>::has, "No default exists for this enum entry.");
    return Entry<ENUM, E>::template get<T>();
}

/// @brief One Entry specialization, for a registry that declares its defaults separately.
#define CONFIG_DEFAULT_ENTRY(E, NAME, DEF) \
    template <> \
    struct Entry<E, E::NAME> \
    { \
        static constexpr bool has = true; \
        template <typename T> \
        static constexpr T get() noexcept { return static_cast<T>(DEF); } \
    };

/**
 * @brief Declares the defaults for a registry not built by DEFINE_CONFIG_GROUP.
 *
 * Registries converted to the X-macro form carry each default inside its
 * FIELD_LIST entry, and DEFINE_CONFIG_GROUP emits these specializations itself.
 * The ones still written by hand keep a separate default list, so this generates
 * the same specializations from it.
 */
#define CONFIG_DEFAULT_TABLE(LIST) LIST(CONFIG_DEFAULT_ENTRY)
}

#endif // REGISTRY_DEFAULT_TABLE_HPP
