/**
 * @file TopologyTable.h
 * @brief EIGRP topology table: routes, successors, feasible successors.
 */

/**
 * @defgroup EIGRP_TOPOLOGY EIGRP Topology
 * @ingroup EIGRP
 * @brief Topology table, DUAL engine, and timer manager for route convergence.
 */

#ifndef EIGRP_TOPOLOGY_TABLE_H
#define EIGRP_TOPOLOGY_TABLE_H

#include <cstdint>
#include <IPAddress.h>
#include <chrono>
#include <map>
#include <unordered_set>
#include "interface/configs/InterfaceType.hpp"

namespace routing::eigrp
{
class EigrpInterface;
class Eigrp;
class Neighbor;
struct ReceivedRoute;
struct SummaryRoute;

/**
 * @brief Classification of a route's origin within the EIGRP topology.
 * @ingroup EIGRP_TOPOLOGY
 */
enum class RouteType
{
    INTERNAL,   ///< Learned from another EIGRP router within the same AS.
    EXTERNAL,   ///< Redistributed into EIGRP from another protocol or AS.
    SUMMARY,    ///< Synthetic aggregate route generated by summarization.
    CONNECTED,  ///< Directly connected prefix injected into the topology table.
    STATIC,     ///< Redistributed static route.
    WITHDRAW,   ///< Sentinel used to signal that a route is being withdrawn (metric infinity).
};

/**
 * @brief Wire-decoded route advertisement received from an EIGRP neighbor.
 * @ingroup EIGRP_TOPOLOGY
 *
 * `ReceivedRoute` is the normalized representation of a single prefix entry
 * extracted from an EIGRP Update, Query, or Reply packet.  It carries all
 * metric components (bandwidth, delay, reliability, load, MTU) so that the
 * local composite metric can be recalculated on arrival.
 *
 * The `external` sub-struct is populated when the route originated outside
 * the EIGRP AS (e.g., redistributed from OSPF or BGP) and carries the
 * redistribution metadata needed for external-route handling.
 *
 * The `wide` sub-struct holds the extended topology information present in
 * EIGRP wide-metric (named-mode) TLVs.
 */
struct ReceivedRoute
{
    types::IPPrefix prefix;
    types::IPAddress nextHop;
    interface::InterfaceKey originInterface;    ///< Interface index on which this route was originally connected or learned.
    uint64_t reportedDistance;    ///< Neighbor's own best metric to the destination (RD).
    uint64_t feasibleDistance;    ///< Total path metric as seen from this router (FD).
    uint64_t delay;
    uint64_t bandwidth;
    uint16_t mtu;
    uint8_t reliability;
    uint8_t load;
    uint8_t hopCount;
    uint32_t tag;
    uint8_t adminDistance;

    /**
     * @brief Redistribution metadata present only on external (EX) routes.
     * @ingroup EIGRP_TOPOLOGY
     */
    struct External
    {
        uint32_t originRouter;   ///< Router ID of the ASBR that injected this route.
        uint32_t originAS;       ///< AS number of the external protocol source.
        uint32_t externalMetric; ///< Metric as it existed in the originating protocol.
        uint8_t type;            ///< External protocol type identifier.
        uint8_t flags;

        /**
         * @brief Bit flags carried in the external route TLV.
         * @ingroup EIGRP_TOPOLOGY
         */
        enum class ExternalFlags : uint8_t
        {
            EXTERNAL = 0x01, ///< Route was redistributed from an external source.
            DEFAULT  = 0x02, ///< Route is being used as a default route candidate.
        };

        inline void setFlag(ExternalFlags bit) { flags |= static_cast<uint8_t>(bit); }
        inline void clearFlag(ExternalFlags bit) { flags &= ~static_cast<uint8_t>(bit); }
        inline void toggleFlag(ExternalFlags bit) { flags ^= static_cast<uint8_t>(bit); }
        inline bool hasFlag(ExternalFlags bit) { return flags & static_cast<uint8_t>(bit); }
    } external;

    /**
     * @brief Extended topology fields present in EIGRP wide-metric (named-mode) TLVs.
     */
    struct Wide
    {
        bool isWide = false;     ///< True if this route was decoded from a wide-metric TLV.
        uint16_t topology = 0;   ///< Multi-topology ID (0 = base topology).
        uint16_t afi = 0;        ///< Address family for this route entry.
        uint32_t rid = 0;        ///< Router ID of the originating router, if present.
        uint8_t priority = 0;    ///< Route priority hint from the originator.

        std::vector<uint8_t> data;
        void allocate(const uint8_t* src, size_t n)
        {
            data.assign(src, src + n);
        }

        uint8_t* bytes() { return data.data(); }
        size_t size() const { return data.size(); }

        Wide() = default;
        ~Wide() = default;
        Wide(const Wide&) = default;
        Wide& operator=(const Wide&) = default;
        Wide(Wide&&) noexcept = default;
        Wide& operator=(Wide&&) noexcept = default;
    } wide;

    uint8_t flags = 0;

    /**
     * @brief Per-route state flags set during processing.
     */
    enum class RouteFlags : uint8_t
    {
        WITHDRAWL  = 0x01, ///< Route is being withdrawn with metric infinity.
        DEFAULT    = 0x02, ///< Route is a candidate default route.
        ACTIVE     = 0x04, ///< Route's prefix is currently in the DUAL Active state.
        REPLICATED = 0x08, ///< Route was replicated from another topology (multi-topology).
    };

    inline void setFlag(RouteFlags bit) { flags |= static_cast<uint8_t>(bit); }
    inline void clearFlag(RouteFlags bit) { flags &= ~static_cast<uint8_t>(bit); }
    inline void toggleFlag(RouteFlags bit) { flags ^= static_cast<uint8_t>(bit); }
    inline bool hasFlag(RouteFlags bit) { return flags & static_cast<uint8_t>(bit); }

    RouteType routeType{};

    ReceivedRoute() = default;
    ~ReceivedRoute() = default;

    ReceivedRoute(const ReceivedRoute&) = default;
    ReceivedRoute& operator=(const ReceivedRoute&) = default;
    ReceivedRoute(ReceivedRoute&&) noexcept = default;
    ReceivedRoute& operator=(ReceivedRoute&&) noexcept = default;
};

struct TopologyEntry;

/**
 * @brief Per-source metric and successor state for one route within a topology entry.
 * @ingroup EIGRP_TOPOLOGY
 *
 * Each unique neighbor that advertises a prefix contributes one `RouteInfo`
 * to the containing @ref TopologyEntry.  The DUAL engine evaluates all
 * `RouteInfo` records for a prefix to determine which neighbors qualify as
 * successors or feasible successors.
 */
struct RouteInfo
{
    RouteInfo(ReceivedRoute& rt) : routeInfo(std::move(rt)) {}
    ReceivedRoute routeInfo;
    bool isSuccessor = false;          ///< True when this is the primary forwarding path (lowest FD).
    bool isFeasibleSuccessor = false;  ///< True when this passes the feasibility condition but is not the successor.
    bool notFeasible = false;          ///< True when this route fails the feasibility condition and cannot be used without a query.
    const TopologyEntry* topology = nullptr; ///< Back-pointer to the containing topology entry.
    std::chrono::steady_clock::time_point lastUpdate; ///< Time of the most recent metric update; used by the deletion timer.
};

/**
 * @brief Tracks whether a topology entry is being suppressed by summary routes on one or more interfaces.
 * @ingroup EIGRP_TOPOLOGY
 *
 * A prefix is suppressed on an interface when a covering summary route has
 * been installed on that interface.  `SuppressionInfo` records the set of
 * active summary routes that suppress this prefix, keyed by interface.
 */
struct SuppressionInfo
{
    std::unordered_set<SummaryRoute*> summaries; ///< Summary routes that are currently suppressing this prefix on the owning interface.

    /**
     * @brief Returns true if this prefix is suppressed by at least one summary.
     */
    bool isSuppressed()
    {
        return !summaries.empty();
    }
};

/**
 * @brief Per-prefix entry in the EIGRP topology table.
 * @ingroup EIGRP_TOPOLOGY
 *
 * `TopologyEntry` aggregates all route advertisements received for one prefix
 * from every neighbor.  It is the unit of state that DUAL operates on:
 * the engine reads and writes the successor/feasible-successor lists and
 * transitions the entry between Passive (stable) and Active (recomputing)
 * states.
 *
 * ## Architectural Role
 * All `TopologyEntry` objects live inside `TopologyTable::topologyEntries`.
 * The @ref DuelEngine reads and mutates entries during recomputation;
 * @ref TopologyController and @ref RouteAggregator hold pointers into the
 * map, so entries must not be erased while any such pointer is live.
 *
 * @warning Do not erase a `TopologyEntry` from the topology table while it
 *          is in the `ACTIVE` state or while any summary route holds a pointer
 *          to it via @ref SuppressionInfo.
 *
 * @see TopologyTable
 * @see DuelEngine
 */
struct TopologyEntry
{
    /**
     * @brief DUAL processing state for this prefix.
     */
    enum class State
    {
        ACTIVE,   ///< Recomputation is in progress; queries have been sent to neighbors.
        PASSIVE,  ///< Stable state; a successor is installed in the RIB.
        POISENED, ///< All paths have been poisoned; awaiting deletion timer expiry.
    };

    types::IPPrefix prefix;
    std::unordered_map<types::IPAddress, RouteInfo> routesBySource; ///< Routes learned from each neighbor.

    std::vector<types::IPAddress> feasibleSuccessors; ///< List of feasible successor neighbors.
    std::vector<types::IPAddress> successors;         ///< List of successor neighbors.

    uint64_t bestFD = std::numeric_limits<uint64_t>::max(); ///< Best feasible distance across all successors; the DUAL loop-free invariant threshold.
    uint8_t bestAD = std::numeric_limits<uint8_t>::max();   ///< Administrative distance of the best path.
    types::IPAddress bestNeighbor = {};                     ///< IP address of the current primary successor neighbor.

    std::unordered_map<interface::InterfaceKey, SuppressionInfo> suppression; ///< Per-interface suppression state, keyed by interface hardware key.

    /**
     * @brief Returns true if this entry is suppressed on the given interface.
     *
     * @param key Hardware interface key to check.
     */
    bool isSuppressed(interface::InterfaceKey key) const
        { return suppression.count(key) > 0; }

    State state = State::PASSIVE;
    std::optional<std::chrono::steady_clock::time_point> valid = std::nullopt; ///< Expiry time for the deletion timer; nullopt while the route is valid.
};

/**
 * @brief Process-wide EIGRP topology table storing all learned and local prefixes.
 * @ingroup EIGRP_TOPOLOGY
 *
 * `TopologyTable` is the central data store for the EIGRP routing process.
 * Every prefix known to this router — whether learned from neighbors, locally
 * connected, or synthesized by summarization — has a @ref TopologyEntry here.
 *
 * The table is mutated exclusively by the @ref DuelEngine and the
 * @ref TopologyController during route processing.  The @ref RouteAggregator
 * inserts synthetic summary entries.
 *
 * ## Architectural Role
 * Owned by `DuelEngine`.  The `TopologyTable` is a pure data store with no
 * timer or scheduler interaction of its own; all timer management is
 * delegated to @ref TimerManager.  The `pruneExpired` method is called
 * periodically by the process scheduler to remove entries whose deletion
 * timer has fired.
 *
 * ## Lifecycle & Ownership
 * Created inside `DuelEngine` at process construction.  All pointers into
 * `topologyEntries` held by other objects (e.g., `RouteInfo::topology`,
 * `SummaryRoute::summaryEntry`) become invalid if the containing entry is
 * erased.  Entries are only erased by `pruneExpired` and `pruneNeighbor`.
 *
 * @see DuelEngine
 * @see TopologyEntry
 */
class TopologyTable
{
public:

    /**
     * @brief Constructs an empty topology table for the given EIGRP process.
     *
     * @param process The owning EIGRP process.
     */
    TopologyTable(Eigrp& process);

    /**
     * @brief Destroys the topology table and all contained entries.
     *
     * All pointers into the table held by other objects become invalid after
     * this destructor returns.
     */
    ~TopologyTable();

    /**
     * @brief Inserts or updates the route advertisement from a neighbor.
     *
     * If an entry for `route.prefix` does not exist it is created.  The
     * `RouteInfo` record for `neighborIp` within that entry is then updated
     * with the new metric values from `route`.
     *
     * @param route      The received route advertisement.
     * @param neighborIp The neighbor that sent this route; nullptr for locally originated routes.
     * @param entry      The topology entry to update (must match `route.prefix`).
     * @return Reference to the updated `RouteInfo` record.
     */
    RouteInfo& addRouteUpdate(const ReceivedRoute& route, const Neighbor* neighborIp, TopologyEntry& entry);

    /**
     * @brief Sets the reported and feasible distance of a route to metric infinity.
     *
     * Used to poison-reverse a path that has become unreachable.  DUAL will
     * recompute successors after this call.
     *
     * @param route      The route record to poison.
     * @param neighborIp IP address of the neighbor whose path is being poisoned.
     * @param entry      The topology entry that contains `route`.
     */
    void markRouteUnreachable(RouteInfo& route, const types::IPAddress& neighborIp, TopologyEntry& entry);

    /**
     * @brief Removes topology entries whose deletion timer has expired.
     *
     * Called periodically by the process scheduler to reclaim memory for
     * prefixes that have been in the `POISENED` state long enough.
     */
    void pruneExpired();

    /**
     * @brief Removes all routes learned from the given neighbor.
     *
     * Called when a neighbor goes down.  Entries that have no remaining route
     * sources after pruning are marked for deletion.
     *
     * @param neighborIp IP address of the neighbor being removed.
     */
    void pruneNeighbor(const types::IPAddress& neighborIp);

    /**
     * @brief Looks up both a topology entry and the specific route from a neighbor.
     *
     * @param prefix   The destination prefix to look up.
     * @param neighbor IP address of the neighbor whose route record is needed.
     * @return Pair of pointers; either or both may be nullptr if not found.
     */
    std::pair<TopologyEntry*, RouteInfo*> findPair(const types::IPPrefix& prefix, const types::IPAddress& neighbor);

    /**
     * @brief Returns the topology entry for `prefix`, creating it if absent.
     *
     * @param prefix Network prefix to look up or create.
     * @return Reference to the (possibly new) topology entry.
     */
    TopologyEntry& ensure(const types::IPPrefix& prefix);

    /**
     * @brief Looks up a topology entry without creating one.
     *
     * @param prefix Network prefix to look up.
     * @return Pointer to the entry, or nullptr if not present.
     */
    TopologyEntry* find(const types::IPPrefix& prefix);

    std::unordered_map<types::IPPrefix, TopologyEntry>& entries() { return topologyEntries; }

private:
    std::unordered_map<types::IPPrefix, TopologyEntry> topologyEntries;

    Eigrp& eigrpProcess; ///< Owning process; used to access config and trigger RIB updates.
};
} // namespace routing::eigrp

#endif // EIGRP_TOPOLOGY_TABLE_H
